@isTest
private class ws_maccabiIsReceiveDocFromArcSOAPTest {

    @isTest
    static void methodTest() {
        ws_maccabiIsReceiveDocFromArcSOAP.xmlStringMaccabi inst = new ws_maccabiIsReceiveDocFromArcSOAP.xmlStringMaccabi('ChannelID', 'PatientID' , 'PatientIDCode', 'LiabilityID', 'CodeSystem', 'CodeSubSystem', 'CodeTypeDocument', 'NameDocument', 'StringFromDoc', 'StyleReceive', 'GeshrSys', 'GeshrSubSys', 'GeshrMikud', 'GeshrNativ', 'NameDocLast');
    }
}